### ISSUE TITLE
Application Security Checklist (OWASP)

### ISSUE THREAD

**Issue by atlsykes** [atlsykes/TrackFinderRN#32]
- [ ] C1: Define Security Requirements

- [ ] C2: Leverage Security Frameworks and Libraries

- [ ] C3: Secure Database Access

- [ ] C4: Encode and Escape Data

- [ ] C5: Validate All Inputs

- [ ] C6: Implement Digital Identity

- [ ] C7: Enforce Access Controls

- [ ] C8: Protect Data Everywhere

- [ ] C9: Implement Security Logging and Monitoring

- [ ] C10: Handle All Errors and Exceptions

See attached doc. for further details.
